name: V.bynum
favicon: null
layout_spectrum: 0.62096
typography_spectrum: 0.97208
title: 'Veyonte Bynum '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f0e9'
    - '#0c0a0f'
    - '#e11226'
    - '#5b5a5f'
    - '#ef71b0'
  brandStrength: 0.4375
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
